image: php:7.3
before_script:
  - apt-get update -qq
  - apt-get install -yqq 
        --no-install-recommends \
        git \
        apt-utils \
        libmemcached-dev \
        libzip-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev 
  
  # Install php-ext-gd
  - docker-php-ext-configure gd \
        --with-jpeg-dir=/usr/lib \
        --with-freetype-dir=/usr/include/freetype2 && \
        docker-php-ext-install gd
  # Install php-ext-zip
  - docker-php-ext-configure zip \
        --with-libzip && \
        docker-php-ext-install zip
  
  # Install composer
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php --install-dir=/usr/bin --filename=composer
  - php -r "unlink('composer-setup.php');"
  
  
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: dissertation.duonglt.net
  script:
    - echo "Deploying"
    - ssh deployer@"$SERVER" -p 2022 "cd /var/www/dissertation && git reset --hard origin/master && git pull origin master && php artisan migrate"
    - "rm -rf ./vendor"
    - "composer install --optimize-autoloader --no-dev && exit"
  only:
    - master
