image: php:7.3
before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: dissertation.duonglt.net
  script:
    - echo "Deploying"
    - ssh deployer@"$SERVER" -p 2022 "cd /var/www/dissertation && git reset --hard origin/master && git pull origin master && php artisan migrate"
    - "composer install --optimize-autoloader --no-dev && exit"
  only:
    - master
